### DISCUSSION TITLE
release 2022-09版本 新版本功能

### DISCUSSION THREAD

**Discussion by data-infra** [tencentmusic/cube-studio#144] [Show and tell]
1、部署：

- 更新：简化istio部署模式为istiod 模式 1.14.1版本，取代1.3.1版本中运维组件太多的问题。在k8s 1.21之上，部署1.15版本istio

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/20157705/204951170-2d5dd4c3-e0cf-4491-8b6d-9de28a5c8d5c.png">

- 更新：修正istio gateway部署端口重复问题，支持非80端口的网关入口

<img width="474" alt="image" src="https://user-images.githubusercontent.com/20157705/204960464-4776d794-387d-4ab6-8c9c-f260f747575f.png">

```
# 添加代理80端口的gateway，需要在istio-ingressgateway 的相关配置中打开80端口
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kubeflow-gateway
  namespace: kubeflow
spec:
  selector:
    istio: ingressgateway         # pod的label
  servers:
  - hosts:
    - '*'
    port:
      number: 80        # svc服务的外部端口，会对应在ingressgateway的容器内启动svc的目标端口，但无法启动80和443内部端口，所以要先修改svc的目标端口，再创建gateway。（也会监听svc目标端口变化进行更改）
      protocol: HTTP   # HTTP协议在第一个创建时就有端口(80端口可能受限)开启，第二个会vs才启动，
---
# 添加代理8080端口的gateway，需要在istio-ingressgateway 的相关配置中打开8080端口
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kubeflow-gateway-8080
  namespace: kubeflow
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      number: 8080
      protocol: HTTP       # TCP 协议需要vs tcp match 端口后才会开启
```

 - 更新：合并命名空间

istio-system：sitio网关和控制面
kubeflow：nni/frameworkcontrolle，kfp/argo，training-operator/spark-operator/paddle-controller-manager，volcano
monitoring：监控体系
infra：cube-studio组件
pipeline：用户任务
service：用户服务
jupyter：用户notebook
automl：用户automl任务

 - 更新：prometheus部署，grafana看板
 
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  image: quay.io/prometheus/prometheus:v2.27.1
  replicas: 1
  retention: 3d
  resources:
    requests:
      memory: 400Mi
```
 
<img width="1626" alt="image" src="https://user-images.githubusercontent.com/20157705/204960976-181fa0da-85ef-4de3-9d21-57ca1b8e89ab.png">

 - 合并部署tfjob/pytorchjob/mpijob/mxnetjob合并到train-operator

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/20157705/204961339-f1cc015f-49b4-4617-9d66-0ebcfa519d80.png">

 - 减少部署镜像

install/kubernetes/all_image.py，如果内网部署，全部拉取
```
# images = kubeflow + kubernetes_dashboard + new_pipline + new_gpu + new_prometheus + istio+ volcano + kube_batch + nni+ cube_studio
images = kubeflow + kubernetes_dashboard + new_pipline + new_gpu + new_prometheus + istio + volcano + nni
```

 - 支持k8s 1.20，1.21，1.22等版本

修改crd配置，部分组件版本，代码

2、平台：

 - 优化前端ui风格，修正前端构建方法

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/20157705/204972363-5320c33d-24e6-4347-805a-03b900d679d6.png">

 - 支持前后端独立部署方式

virtual service 代理到前端，前端nginx代理到后端

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/20157705/204972395-890e2571-01dc-48ec-9b93-6a89fe6cebd4.png">

- 新增离线表

<img width="1666" alt="image" src="https://user-images.githubusercontent.com/20157705/204979176-b5487c58-d1e6-4b5c-926e-7acd46566303.png">

 - 指标

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/20157705/204979603-5debadd2-9677-4ecf-887d-35c2f3ee4336.png">

 - 维表

管理远程表

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/20157705/204980891-142e51f8-b47e-42a5-9073-5b65b067622a.png">

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/20157705/204980929-581fe0c1-350d-48c3-a1f4-44f524cc3b05.png">

 - 数据集

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/20157705/204980985-c760461c-4cd3-433c-b872-679d6bde41b8.png">

 - 数据etl

需要对接调度平台

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/20157705/204981155-cc3705e7-1ad3-459f-a979-b55e3531aec0.png">

 - 模型管理功能

一键发布到服务

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/20157705/204981824-aef2fa05-9037-4cac-96a1-bfbd289f7492.png">

 - 修改水印和pipeline跳转链接

后端接口，控制重定向

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/20157705/204982758-fd569368-feb2-44f6-b2ea-72305ff4df1a.png">

 - 禁用jupyter的xsrf和网关请求大小限制

上传下载中，或使用过程中的一些报错

 - 支持k8s共享内存的自动挂载。

```
volumes:
    - name: tz-config
      hostPath:
        path: /usr/share/zoneinfo/Asia/Shanghai
        type: ''
    - name: dshm
      emptyDir: {}

      ...

      volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
        - name: dshm
          mountPath: /dev/shm
```
 - 补充coredns的配置，支持内网特殊dns解析

内网host解析，使用[coredns配置](https://github.com/tencentmusic/cube-studio/blob/master/install/kubernetes/rancher/coredns.yaml)。

```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . "/etc/resolv.conf"
        cache 30
        loop
        reload
        loadbalance
    }
    oa.com:53 {
      errors
      cache 30
      hosts {
        1.1.1.1    example1.oa.com
        2.2.2.2    example2.oa.com
        fallthrough
      }
      forward . 4.4.4.4 5.5.5.5
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
```

- 添加全局用户pod的监控，添加用户任务资源占用监控，修正部分监控页面打开bug

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/20157705/205001098-48a62fdd-1bef-41cb-a29b-5432e55c504f.png">

- 添加推理服务sidecar功能，支持ip端口形式的流量监控。

<img width="704" alt="image" src="https://user-images.githubusercontent.com/20157705/205001331-79ee1d27-9d92-47ba-aa8b-41de305feb94.png">

 - 添加服务的帮助链接

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/20157705/205001808-1f11033b-2468-4266-8700-2eb9d5009a05.png">

- 支持右侧菜单自定义配置，添加bug report链接

<img width="1570" alt="image" src="https://user-images.githubusercontent.com/20157705/205002707-fe443669-40af-4649-b8e5-e1c0964437f2.png">

 - 支持多集群下，不同泛域名

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/20157705/205007508-e22bb795-6a08-4c12-8d0d-d0b3b3dd684c.png">

 - 添加支持bigdata machinelearning deeplearning版本jupyter，
 
<img width="997" alt="image" src="https://user-images.githubusercontent.com/20157705/205012245-05eca552-caa3-4b86-80db-73360e955c4c.png">

 - 支持ssh直连notebook，支持notebook中hadoop，spark，flink数据分析

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/20157705/205012812-945a3487-c1a8-434a-90ba-e8a939826a93.png">

- 支持notebook中hadoop，spark，flink数据分析

<img width="1461" alt="image" src="https://user-images.githubusercontent.com/20157705/205015821-7abdec2c-1214-4673-bc52-36d46c902ead.png">

 - 添加支持服务部署中内外双网卡和单域名模式

<img width="757" alt="image" src="https://user-images.githubusercontent.com/20157705/205016990-e75fa123-2940-4cce-96af-9d352ec7334d.png">

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/20157705/205016935-7038737a-0757-44cd-a19f-bf4a71a5ef75.png">

 - 添加支持密码修改,支持跨域共享cookie认证，和ifram嵌入跨域问题,

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/20157705/205017125-6bdece79-d1e9-433e-8f07-03afbd0dd9f0.png">

```
@app.after_request
def myapp_after_request(resp):
    try:
        if g.user and g.user.username:

            resp.set_cookie('myapp_username', g.user.username,domain=conf.get('COOKIE_DOMAIN',None) if conf.get('COOKIE_DOMAIN',None) else None)  # 设置用户信息传递

```

 - 增加任务跳过功能，增加项目组切换后，挂载自动补充

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/20157705/205017412-a78f6e93-6f40-41f8-a7ef-2f9877a6c49e.png">

 - 添加数据集/模型/推理/内部服务/模板/pipeline示例，添加chatbot/cartoonize/openpose/face/yolo/wenet等内部服务示例，添加triton/tfserving/torchserver镜像构建和推理demo

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/20157705/205017507-0ab82660-4857-4802-a380-f14e6e579780.png">

- 添加mpi/spark-serverless/horovod/paddle/mxnet/tfjob-k8s/分布式训练，添加hadoop模板，支持spark任务提交，添加ner中文实体识别模板，修正模板的使用说明和参数说明，

<img width="834" alt="image" src="https://user-images.githubusercontent.com/20157705/205017700-2fe195c3-9eaf-4bd9-95a6-638e5811dc5c.png">

- github补充wiki，代码规范升级,修正数个isues bug

去除无效引用，https://github.com/tencentmusic/cube-studio/wiki

3、aihub:

- 平台添加aihub 应用市场查看

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/20157705/205018017-7b945659-3ce7-454a-92b3-93a4216e04c5.png">

- 开源aihub python sdk

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/20157705/205018122-cbe899ed-2628-474c-9d36-011e798d8261.png">

- 深度学习，添加算法模型animegan,ddddocr,deoldify,detectron2,face-paint,gfpgan,humanseg,paddleocr,panoptic,stable-diffusion,yolov3

<img width="890" alt="image" src="https://user-images.githubusercontent.com/20157705/205018194-0a2efa1a-4042-4eb6-91f9-22e45a598dff.png">

- 传统机器学习，添加算法示例

AdaBoost,Bayesian,CRF,CatBoost,FM,HMM,LDA,MCMC,MEM,PCA,SVD,SVM,decision_tree,gbdt,kmean,knn,lightGBM,linear_regression,logistic_regression,neural_networks,random_forest,xgboost,关联分析,最小生成树,极大似然估计,聚类,集成学习

<img width="645" alt="image" src="https://user-images.githubusercontent.com/20157705/205018254-ad3e288e-f75a-41e2-a839-99972181d659.png">
