### ISSUE TITLE
路由增加https反代,login跳转返回http的协议

### ISSUE THREAD

**Issue by lkad** [tencentmusic/cube-studio#189]
访问地址https://xxx.xxx.xxx
重定向到http://xxx.xxx.xxxx/login/? 导致无法访问。
反代软件: traefik 2.8 ,反代配置
```
http:
  routers:
    stuio-kbs:
      rule: "Host(`xxx.xxx.xxx`)"
      service: stuio-kbs
      entrypoints: websecure
      tls:
           certResolver: myresolver
           domains:
             - sans:
                 - "*.xxx.xxx"
  services:
    stuio-kbs:
      loadBalancer:
       servers:
         - url: "http://集群masterIP"
     ```
