### ISSUE TITLE
4.1号版本 在线开发生成vs规则后导致整个访问都是404

### ISSUE THREAD

**Issue by lkad** [tencentmusic/cube-studio#196]
生成jyputer后新增了一条vs的规则后，访问整个cube-studio都是404
下面是新增的规则.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: notebook-jupyter-admin-a2eb
  namespace: jupyter
spec:
  gateways:
    - kubeflow/kubeflow-gateway
  hosts:
    - xxx.xxx.xxx.xxx
  http:
    - match:
        - uri:
            prefix: /notebook/jupyter/admin-a2eb/
      rewrite:
        uri: /
      route:
        - destination:
            host: admin-a2eb.jupyter.svc.cluster.local
            port:
              number: 3000
      timeout: 300s

```
原始dashboard的规则。
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"infra-kubeflow-dashboard","namespace":"infra"},"spec":{"gateways":["kubeflow/kubeflow-gateway"],"hosts":["*"],"http":[{"route":[{"destination":{"host":"kubeflow-dashboard-frontend.infra.svc.cluster.local","port":{"number":80}}}]}]}}
  name: infra-kubeflow-dashboard
  namespace: infra
spec:
  gateways:
    - kubeflow/kubeflow-gateway
  hosts:
    - '*'
  http:
    - route:
        - destination:
            host: kubeflow-dashboard-frontend.infra.svc.cluster.local
            port:
              number: 80

```
